---

- hosts: myapp-db,myapp-web
  become: False
  gather_facts: False
  roles:
    - { role: bootstrap-python,       tags: "bootstrap" }

- hosts: myapp-db
  become: True
  gather_facts: True
  roles:
    - { role: common,                 tags: "common" }
    - { role: myapp-db,               tags: "myapp-db" }

- hosts: myapp-web
  become: True
  gather_facts: True
  roles:
    - { role: common,                 tags: "common" }
    - { role: myapp-web,              tags: "myapp-web" }
